// import './globals.css';
// import '../../../web-client/src/index.scss';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta content="noindex" name="robots" />
        <meta
          content="REPLACE_ME_LAST_DEPLOYED"
          id="last-deployed"
          name="date"
        />
        <title>
          U.S. Tax Court Electronic Filing and Case Management System
        </title>
        <link href="/site.webmanifest" rel="manifest" />
        <link color="#5bbad5" href="/safari-pinned-tab.svg" rel="mask-icon" />
        <meta content="#da532c" name="msapplication-TileColor" />
        <meta content="#ffffff" name="theme-color" />
        {/* <script defer src="/index-public.js" type="module"></script> */}
      </head>
      <body>
        <div id="app-public">{children}</div>
        <div id="modal-root"></div>
        <div id="dwtcontrolContainer"></div>
      </body>
    </html>
  );
}
