#!/bin/bash

[ -z "$1" ] && echo "The branch name to check must be provided as the \$1 argument." && exit 1

BRANCH=$1

if [[ $BRANCH == 'develop' ]] ; then
  
  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_DEV}"
  export ES_INSTANCE_TYPE="t2.small.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY="${CIRCLE_HONEYBADGER_API_KEY_DEV}"
  export DISABLE_EMAILS="${DISABLE_EMAILS_DEV}"
  export ES_VOLUME_SIZE="10"
  export ENV="dev"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_DEV}"
  export ZONE_NAME="${ZONE_NAME_DEV}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_DEV}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_DEV}"

elif [[ $BRANCH == 'experimental1' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_EXP}"
  export ES_INSTANCE_TYPE="t2.small.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_EXP1}"
  export ES_VOLUME_SIZE="10"
  export ENV="exp1"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_EXP1}"
  export ZONE_NAME="${ZONE_NAME_EXP1}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_EXP1}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_EXP1}"

elif [[ $BRANCH == 'experimental2' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_EXP}"
  export ES_INSTANCE_TYPE="t2.small.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_EXP2}"
  export ES_VOLUME_SIZE="10"
  export ENV="exp2"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_EXP2}"
  export ZONE_NAME="${ZONE_NAME_EXP2}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_EXP2}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_EXP2}"

elif [[ $BRANCH == 'experimental3' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_EXP}"
  export ES_INSTANCE_TYPE="t2.small.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY="${CIRCLE_HONEYBADGER_API_KEY_EXP3}"
  export DISABLE_EMAILS="${DISABLE_EMAILS_EXP3}"
  export ES_VOLUME_SIZE="10"
  export ENV="exp3"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_EXP3}"
  export ZONE_NAME="${ZONE_NAME_EXP3}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_EXP3}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_EXP3}"

elif [[ $BRANCH == 'irs' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_IRS}"
  export ES_INSTANCE_TYPE="t2.small.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_IRS}"
  export ES_VOLUME_SIZE="10"
  export ENV="irs"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_IRS}"
  export ZONE_NAME="${ZONE_NAME_IRS}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_IRS}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_IRS}"

elif [[ $BRANCH == 'staging' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_STG}"
  export ES_INSTANCE_TYPE="t2.medium.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY="${CIRCLE_HONEYBADGER_API_KEY_STG}"
  export DISABLE_EMAILS="${DISABLE_EMAILS_STG}"
  export ES_VOLUME_SIZE="10"
  export ENV="stg"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_STG}"
  export ZONE_NAME="${ZONE_NAME_STG}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_STG}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_STG}"

elif [[ $BRANCH == 'test' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_TEST}"
  export ES_INSTANCE_TYPE="m5.large.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_TEST}"
  export ES_VOLUME_SIZE="350"
  export ENV="test"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_TEST}"
  export ZONE_NAME="${ZONE_NAME_TEST}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_TEST}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_TEST}"

elif [[ $BRANCH == 'migration' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_MIG}"
  export ES_INSTANCE_TYPE="m5.large.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_MIG}"
  export ES_VOLUME_SIZE="350"
  export ENV="mig"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_MIG}"
  export ZONE_NAME="${ZONE_NAME_MIG}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_MIG}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_MIG}"

elif [[ $BRANCH == 'master' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_PROD}"
  export ES_INSTANCE_TYPE="m5.large.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_MASTER}"
  export ES_VOLUME_SIZE="100"
  export ENV="prod"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_PROD}"
  export ZONE_NAME="${ZONE_NAME_PROD}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_PROD}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_PROD}"

elif [[ $BRANCH == 'dawson' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_DAWSON}"
  export ES_INSTANCE_TYPE="t2.small.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_DAWSON}"
  export ES_VOLUME_SIZE="100"
  export ENV="daw"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_PROD}"
  export ZONE_NAME="${ZONE_NAME_PROD}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_PROD}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_PROD}"

elif [[ $BRANCH == 'prod' ]] ; then

  export ES_INSTANCE_COUNT="3"
  export DYNAMSOFT_PRODUCT_KEYS="${DYNAMSOFT_PRODUCT_KEYS_PROD}"
  export ES_INSTANCE_TYPE="m5.xlarge.elasticsearch"
  export CIRCLE_HONEYBADGER_API_KEY=""
  export DISABLE_EMAILS="${DISABLE_EMAILS_PROD}"
  export ES_VOLUME_SIZE="350"
  export ENV="prod"
  export EFCMS_DOMAIN="${EFCMS_DOMAIN_PROD}"
  export ZONE_NAME="${ZONE_NAME_PROD}"
  export IRS_SUPERUSER_EMAIL="${IRS_SUPERUSER_EMAIL_PROD}"
  export BOUNCED_EMAIL_RECIPIENT="${BOUNCED_EMAIL_RECIPIENT_PROD}"

else
  exit 1;
fi
