version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker build -t efcms -f Dockerfile .
      - run: docker run efcms /bin/sh -c 'cd shared && ./run-shellcheck.sh'
      - run: docker run efcms /bin/sh -c 'cd shared && npm run lint'
      - run: docker run efcms /bin/sh -c 'cd shared && npm run test'