name: Node.js CI - Client Unit Tests

on:
  pull_request:

jobs:
  Client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [0, 1, 2, 3]
    env:
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Test Client Unit
        run: |
          export TESTFILES=$(npx ts-node split-tests-glob.ts -unit)
          npm run test:client:unit:ci
