name: Create an intermediate branch to test

on:
  pull_request:
    branches: [test]
    type:
      - opened

jobs:
  create-intermediate-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Set Git config
        run: |
          git config --local user.email "jabu@flexion.us"
          git config --local user.name "Joshua Abu"
      - name: Create Intermediate branch
        run: |
          # Initialize variables
          destination_branch=test
          feature_branch=${{ github.head_ref }}
          intermediate_branch="${feature_branch}-intermediate-to-test"

          # Get Test branch
          git fetch --unshallow
          git checkout test
          git pull

          # Create a copy of the destination branch
          git checkout -b "${intermediate_branch}" "${destination_branch}"

          # Merge the feature branch into the intermediate branch
          git merge "origin/${feature_branch}"

          # Push the new intermediate to remote
          git push -u origin "${intermediate_branch}"
      - name: Make PR of Intermediate branch to Test
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'PR setup for intermediate branch of ${{ github.head_ref }} to test'
          title: '${{ github.head_ref }} intermediate to test'
          body: 'PR to test.'
          base: test
          labels: automated-pr
          branch: ${{ github.head_ref }}
