name: Create an intermediate branch to experimental3

on:
  pull_request:
    branches: [experimental3]
    type:
      - opened

jobs:
  check-for-intermediate-branch:
    runs-on: ubuntu-latest
    outputs:
      create-branch-flag: ${{ steps.check_branch.outputs.create-branch-flag }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "jabu@flexion.us"
          git config --local user.name "Joshua Abu"

      - name: Set flag
        id: check_branch
        run: |
          feature_branch=${{ github.head_ref }}
          intermediate_branch="${feature_branch}-intermediate-to-experimental3"

          # get intermediate branch related commits in both repos
          sha_of_int_branch=$(git ls-remote origin $intermediate_branch)

          if [[ -n "${sha_of_int_branch}" ]]
          then
            echo "create-branch-flag=false" >> "$GITHUB_OUTPUT"
          else
            echo "create-branch-flag=true" >> "$GITHUB_OUTPUT"
          fi
      - name: LOG FLAG
        run: |
          echo "FLAG IS: ${{ steps.check_branch.outputs.create-branch-flag }}"

#######
