name: Node.js Unit Test

on:
  push:
    branches: [develop, experimental1, master]
  pull_request:
    branches: [develop, experimental1, master]

jobs:
  linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: NPM Install
        run: npm ci --no-optional && npm rebuild node-sass

      - name: Shared Unit Tests
        run: npm run test:shared

      - name: API Unit Tests
        run: npm run test:api
